"""AI profile photos — dating-app CLICHÉS, generated, cached on the volume.

Instead of plain StyleGAN faces, each profile gets a wholesome-but-absurd dating
cliché (man holding a fish, Santorini rooftop, sedated-tiger tourist photo, gym
mirror selfie, summit victory pose, …) generated by a text-to-image model
(Pollinations, key-less). Every image is 100% AI slop — exactly the pitch.

Generated once per profile id, downscaled/recompressed, and cached under /data
(persistent volume). A scheduled job pre-warms ahead of demand. Everything
degrades gracefully: disabled or a failed generation → None → SVG avatar.
"""

from __future__ import annotations

import hashlib
import io
import os
import threading
import time
import urllib.parse
import urllib.request
from typing import Any

from PIL import Image

# Cache is versioned by style so switching the photo style regenerates cleanly.
STYLE = os.environ.get("FACE_STYLE", "cliche-v1")
FACES_DIR = os.path.join(os.environ.get("FACES_BASE", "/data/faces"), STYLE)
ENABLED = os.environ.get("FACES_ENABLED", "1") == "1"
MODEL = os.environ.get("FACE_MODEL", "flux")
SIZE = 640

# Wholesome, clothed dating-app photo clichés (SFW). Researched tropes across
# Tinder/Bumble/Hinge — the fish, the tiger, the Santorini shot, the summit, etc.
CLICHES = [
    "a man proudly holding a large freshly-caught fish on a boat",
    "a person posing awkwardly next to a sedated tiger at a dubious tourist attraction",
    "a woman in a flowy white dress on a Santorini rooftop with blue domes at golden hour",
    "a man taking a flexing mirror selfie in a gym in workout clothes",
    "a person at a mountain summit throwing both arms up in triumph with hiking poles",
    "a group of five friends at a bar, impossible to tell which one has the profile",
    "a man in a suit holding a drink at someone else's wedding",
    "a person holding a baby that is obviously their nephew, not theirs",
    "a woman doing a yoga tree pose on a cliff at sunrise",
    "a man holding a flight of craft beers at a brewery, very pleased",
    "a person riding a camel in front of desert pyramids, squinting into the sun",
    "a woman at a music festival wearing a flower crown",
    "a person crouching to pet a stray dog on a beach abroad",
    "a man playing acoustic guitar on a couch with his eyes closed, feeling it",
    "a flattering car selfie with sunglasses and good window light",
    "a woman holding an enormous brunch mimosa, laughing at nothing",
    "a person skiing in full goggles and helmet so you cannot see their face",
    "a moody black-and-white headshot staring thoughtfully into the distance",
    "a person scuba diving underwater giving an enthusiastic thumbs up",
    "a woman posing in front of a colorful graffiti street-art mural",
    "a man at a backyard bbq holding grill tongs like a trophy",
    "a person at Machu Picchu with a llama photobombing the shot",
    "a woman with a latte and an open book arranged aesthetically on a cafe table",
    "a person crossing a marathon finish line, sweaty and triumphant",
    "a man leaning on an expensive sports car that is clearly not his",
    "a woman in a summer dress standing in a sunflower field",
    "a person on a sailboat holding a glass of wine with wind in their hair",
    "a man cuddling a rescue puppy with a caption energy of 'she completes me'",
    "a person doing the pinch-the-top-of-the-Eiffel-Tower forced-perspective pose",
    "a person skydiving mid-freefall giving a thumbs up, cheeks flapping",
]
_SUFFIX = ", candid amateur smartphone dating-app profile photo, natural lighting, slightly awkward composition"

_UA = {
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36",
}
_locks: dict[str, threading.Lock] = {}
_guard = threading.Lock()


def _lock_for(fid: str) -> threading.Lock:
    with _guard:
        return _locks.setdefault(fid, threading.Lock())


def _safe(fid: str) -> str:
    return "".join(c for c in fid if c.isalnum() or c in "-_")  # no path traversal


def _hash(fid: str) -> int:
    return int(hashlib.sha256(fid.encode()).hexdigest(), 16)


def cliche_for(fid: str) -> str:
    return CLICHES[_hash(fid) % len(CLICHES)]


def _source_url(fid: str) -> str:
    prompt = urllib.parse.quote(cliche_for(fid) + _SUFFIX)
    seed = _hash(fid) % 1_000_000
    return f"https://image.pollinations.ai/prompt/{prompt}?width={SIZE}&height={SIZE}&seed={seed}&nologo=true&model={MODEL}"


def path_for(fid: str) -> str:
    return os.path.join(FACES_DIR, f"{_safe(fid)}.jpg")


def get(fid: str, timeout: int = 30) -> str | None:
    """Return a local path to the cached cliché photo for `fid`, generating +
    caching on first use. Returns None if disabled or generation fails (the
    text-to-image model can be slow; the pre-warmer uses a longer timeout)."""
    if not ENABLED or not _safe(fid):
        return None
    p = path_for(fid)
    if os.path.exists(p):
        return p
    with _lock_for(fid):
        if os.path.exists(p):  # double-check after acquiring the lock
            return p
        try:
            req = urllib.request.Request(_source_url(fid), headers=_UA)
            with urllib.request.urlopen(req, timeout=timeout) as r:  # noqa: S310 (fixed https source)
                raw = r.read()
            img = Image.open(io.BytesIO(raw)).convert("RGB")
            if img.width != SIZE or img.height != SIZE:
                img = img.resize((SIZE, SIZE), Image.Resampling.LANCZOS)
            os.makedirs(FACES_DIR, exist_ok=True)
            tmp = p + ".tmp"
            img.save(tmp, "JPEG", quality=82, optimize=True)
            os.replace(tmp, p)  # atomic; concurrent readers never see a partial file
            return p
        except Exception:
            return None


# ── The growing corpus ────────────────────────────────────────────────────
# A scheduled job (see .github/workflows/warm.yml) calls warm() periodically to
# bank the next chunk of faces onto the volume, so the ready corpus keeps
# growing over time toward "always fresh, effectively infinite".

_FRONTIER = os.path.join(FACES_DIR, ".frontier")


def _read_frontier() -> int:
    try:
        with open(_FRONTIER) as f:
            return int(f.read().strip() or "0")
    except (OSError, ValueError):
        return 0


def _write_frontier(n: int) -> None:
    try:
        os.makedirs(FACES_DIR, exist_ok=True)
        with open(_FRONTIER, "w") as f:
            f.write(str(n))
    except OSError:
        pass


def count_cached() -> int:
    try:
        return sum(1 for f in os.listdir(FACES_DIR) if f.endswith(".jpg"))
    except OSError:
        return 0


def corpus_stats() -> dict[str, Any]:
    return {"cached_faces": count_cached(), "frontier": _read_frontier(), "faces_enabled": ENABLED}


_warm_lock = threading.Lock()


def warm(chunk: int = 40) -> dict[str, Any]:
    """Pre-generate the next `chunk` cliché photos onto the volume. Gentle."""
    if not ENABLED:
        return {"enabled": False}
    start = _read_frontier()
    warmed = 0
    for i in range(start, start + chunk):
        if get(str(i), timeout=120):  # generation can be slow; the warmer can wait
            warmed += 1
        time.sleep(0.5)  # be polite to the generator
    _write_frontier(start + chunk)
    return {"warmed": warmed, "frontier": start + chunk, "cached_faces": count_cached()}


def warm_async(chunk: int = 40) -> dict[str, Any]:
    """Kick off warming in the background and return immediately — image
    generation is slow, so we never block the HTTP request (or trip proxy
    timeouts). A lock prevents overlapping runs."""
    if not ENABLED:
        return {"enabled": False}
    if _warm_lock.locked():
        return {"status": "already running", **corpus_stats()}

    def _run() -> None:
        with _warm_lock:
            warm(chunk)

    threading.Thread(target=_run, daemon=True).start()
    return {"status": "started", "chunk": chunk, **corpus_stats()}
