"""Ever-growing text banks — taglines, bios, names, profile prompts, interstitial
cards, and landing pitches, periodically generated by the LLM and appended to
JSON banks on the /data volume. Served profiles and the frontend draw from
curated + generated pools, so the content keeps getting fresher over time.

Robust by design: generation needs a real LLM key (see llm.py); until then the
banks just stay empty and everything falls back to the curated lists. A scheduled
job (warm.yml) calls top_up periodically so the banks grow.
"""

from __future__ import annotations

import json
import os
import threading
from typing import Any

from . import llm

TEXT_DIR = os.environ.get("TEXT_DIR", "/data/text")
CAP = 3000  # max items kept per bank

VOICE = ("for 'Unhinged', a parody dating app where every profile and photo is "
         "100% AI-generated fake and proud of it. Voice: witty, deadpan, self-aware, "
         "a little chaotic. SFW. Genuinely funny and original, not generic.")

# kind -> (prompt, kind_of_parse)
_SPEC: dict[str, tuple[str, str]] = {
    "taglines": (f"Write {{n}} fresh dating-profile taglines {VOICE} Each under 60 chars, "
                 "no emojis, no quotes, no numbering. Output only the taglines, one per line.", "line"),
    "bios": (f"Write {{n}} fresh dating-profile bios {VOICE} Each 1-2 sentences, under 160 chars, "
             "no emojis, no numbering. Output only the bios, one per line.", "line"),
    "names": (f"Write {{n}} absurd, funny fake dating-app display names {VOICE} Each under 22 chars "
              "(e.g. 'Chad.exe', 'Neuralnetta', '404_Notfound'). One per line, no numbering.", "line"),
    "pitches": (f"Write {{n}} punchy one-line marketing taglines {VOICE} Lean into 'every dating app "
                "is mostly fake, we're just honest'. Under 90 chars, one per line, no numbering.", "line"),
    "cards": (f"Write {{n}} short interstitial 'reminder' cards {VOICE} Each is a bold HEADER and a "
              "one-sentence body. Format EXACTLY 'header :: body', one per line, no numbering.", "pair"),
    "prompts": (f"Write {{n}} dating-profile prompt+answer pairs {VOICE} The prompt is a classic "
                "dating-app question, the answer is unhinged. Format EXACTLY 'prompt :: answer', "
                "one per line, no numbering.", "pair"),
}

_locks: dict[str, threading.Lock] = {}
_guard = threading.Lock()
_cache: dict[str, tuple[float, list[Any]]] = {}
_gen_lock = threading.Lock()


def _path(kind: str) -> str:
    return os.path.join(TEXT_DIR, kind + ".json")


def bank(kind: str) -> list[Any]:
    """Cached read of a bank (reloads when the file changes)."""
    p = _path(kind)
    try:
        mt = os.path.getmtime(p)
    except OSError:
        return []
    cached = _cache.get(kind)
    if not cached or cached[0] != mt:
        try:
            with open(p) as f:
                data = json.load(f)
        except (OSError, json.JSONDecodeError):
            data = []
        _cache[kind] = (mt, data)
    return list(_cache[kind][1])


def _clean(s: str) -> str:
    return s.strip().strip('"').lstrip("-•*0123456789. ").strip().strip('"').strip()


def _parse(kind_of_parse: str, txt: str) -> list[Any]:
    out: list[Any] = []
    for line in txt.splitlines():
        if kind_of_parse == "pair":
            if "::" not in line:
                continue
            a, b = line.split("::", 1)
            a, b = _clean(a), b.strip()
            if 2 <= len(a) <= 60 and 3 <= len(b) <= 160:
                out.append({"q": a, "a": b})
        else:
            s = _clean(line)
            if 3 <= len(s) <= 170:
                out.append(s)
    return out


def _key(item: Any) -> str:
    return (item["a"] if isinstance(item, dict) else str(item)).lower()


def top_up(kind: str, n: int = 12) -> int:
    """Generate ~n new items for a kind and append the unique ones. Returns count added."""
    spec = _SPEC.get(kind)
    if not spec:
        return 0
    prompt, parse = spec
    txt = llm.chat([{"role": "user", "content": prompt.format(n=n)}], max_tokens=700, temperature=1.1)
    new = _parse(parse, txt)
    if not new:
        return 0
    with _lock_for(kind):
        existing = bank(kind)
        have = {_key(x) for x in existing}
        added = [x for x in new if _key(x) not in have]
        if not added:
            return 0
        merged = (existing + added)[-CAP:]
        os.makedirs(TEXT_DIR, exist_ok=True)
        tmp = _path(kind) + ".tmp"
        with open(tmp, "w") as f:
            json.dump(merged, f)
        os.replace(tmp, _path(kind))
        _cache.pop(kind, None)
        return len(added)


def _lock_for(kind: str) -> threading.Lock:
    with _guard:
        return _locks.setdefault(kind, threading.Lock())


def stats() -> dict[str, int]:
    return {k: len(bank(k)) for k in _SPEC}


def top_up_all(n: int = 10) -> dict[str, Any]:
    if not llm.has_key():
        return {"skipped": "no LLM key"}
    return {k: top_up(k, n) for k in _SPEC}


def top_up_async(n: int = 10) -> dict[str, Any]:
    if _gen_lock.locked():
        return {"status": "already running", **stats()}

    def _run() -> None:
        with _gen_lock:
            top_up_all(n)

    threading.Thread(target=_run, daemon=True).start()
    return {"status": "started", **stats()}
